version: "3"

services:
  mc:
    image: itzg/minecraft-server
    volumes:
      - mc:/data
      - ./init-world:/worlds/world
    ports:
      - 25565:25565
    environment:
      MOTD: "§3Okie§2Craft§r Private Server"
      EULA: "TRUE"
      TYPE: SPIGOT
      SPIGET_RESOURCES: 60623
      OPS: "jeremy85"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      VERSION: "1.18.1"
      DIFICULTY: "normal"
      RCON_PASSWORD: ${RCON_PASSWORD}
      WORLD: /worlds/world
    tty: true
    stdin_open: true
    restart: unless-stopped
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "24h"
    volumes:
      - ./mc-data:/data:ro
      - ./backups:/backups
    network_mode: "service:mc"
volumes:
  mc: {}
  
  