version: "3"

services:
  mc:
    image: itzg/minecraft-server
    volumes:
      - ./mc-data:/data
    ports:
      - 25565:25565
    environment:
      MOTD: "§3Oakie§2Craft§r Private Server"
      EULA: "TRUE"
      TYPE: "PAPER"
      SPIGET_RESOURCES: 60623
      OPS: "jeremy85"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      VERSION: "1.18.1"
      DIFICULTY: "normal"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28016
      VIEW_DISTANCE: 16
      SIMULATION_DISTANCE: 16
      MEMORY: "12G"
    tty: true
    stdin_open: true
    restart: unless-stopped
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "24h"
    volumes:
      - ./mc-data:/data:ro
      - ./backups:/backups
    network_mode: "service:mc"